#!/usr/bin/env python

# MBUtil: a tool for MBTiles files
# Supports importing, exporting, and more
#
# (c) Development Seed 2012
# (c) 2016 ePi Rational, Inc.
# Licensed under BSD
#
# The implementation lives in mbutil/cli.py so it can be installed as a
# console_scripts entry point. This shim keeps ./mb-util working in a checkout
# and as the Docker entrypoint.

from mbutil.cli import main

if __name__ == '__main__':
    main()
